### ISSUE TITLE
Inquiry on Code Release Date for Inspiring Project

### ISSUE THREAD

**Issue by fighting-Zhang** [whieya/Learning-to-compose#1]
Hello,

Thank you for this very inspiring work; I am eager to try out its effects. Could you please let me know when the code will be released?

Thank you for your time and consideration.

**Comment by sivannavis** [comment]
Hi @whieya ! I have the very same question. Great work and hope to see the codes soon!

**Comment by mchivuku** [comment]
Hi @whieya , i have attended your talk at iclr and very much interested in trying out your code. Looking forward to seeing your code. Thank you

**Comment by whieya** [comment]
Hi, sorry for the late reply. We have released the code. Please ask me if you have any questions.
